# Generated by Django 6.0.5 on 2026-05-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(default='Student', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('done', 'Completed'), ('no_show', 'No-show')], default='waiting', max_length=20)),
                ('sector', models.CharField(choices=[('Bank', 'Bank'), ('Library', 'Library'), ('Office', 'UAP Office'), ('Canteen', 'Canteen')], max_length=20)),
                ('token', models.CharField(max_length=10)),
                ('position', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(default='Guardian', max_length=100)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queue_app.student')),
            ],
        ),
    ]
