# Generated by Django 6.0.5 on 2026-05-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='name',
            field=models.CharField(default='Guardian', max_length=100),
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queue_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Bank', 'Bank'), ('Library', 'Library'), ('Office', 'UAP Office'), ('Canteen', 'Canteen')], max_length=20)),
                ('token', models.CharField(max_length=10)),
                ('position', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_app.student')),
            ],
        ),
    ]
