# Generated by Django 6.0.5 on 2026-05-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='status',
        ),
    ]
