# Generated by Django 6.0.5 on 2026-05-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_sector_student_profile_image_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='sector',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Library', 'Library'), ('Office', 'UAP Office'), ('Canteen', 'Canteen')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='queue',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='guardian',
            name='name',
            field=models.CharField(default='Guardian', max_length=100),
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queue_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='queue',
            name='token',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
