# Generated by Django 4.2.30 on 2026-05-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_guardian_name_guardian_student_student_name_queue'),
        ('queue_app', '0003_alter_queue_sector_remove_queue_estimated_time_and_more'),
    ]

    operations = [
    ]
