# Generated by Django 4.2.30 on 2026-05-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_student_image'),
        ('queue_app', '0005_alter_guardian_id_alter_queue_id_alter_student_id'),
    ]

    operations = [
    ]
