# Generated by Django 4.2.30 on 2026-05-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0007_queue_status_alter_guardian_id_alter_queue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
