# Generated by Django 6.0.4 on 2026-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('token_number', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=100)),
                ('waiting_time', models.IntegerField()),
                ('service_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
