# Generated by Django 6.0.5 on 2026-05-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_queuehistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
