# Generated by Django 4.2.30 on 2026-05-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_queuehistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuehistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
