<<<<<<< HEAD:smartqueue/feedback/migrations/0001_initial.py
# Generated by Django 6.0.5 on 2026-05-09 03:49
=======
# Generated by Django 4.2.30 on 2026-05-09 04:10
>>>>>>> 6a7a41b34536667b9af969cbe9c39fb09d7988d1:smartqueue/notifications/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD:smartqueue/feedback/migrations/0001_initial.py
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
=======
                ('is_read', models.BooleanField(default=False)),
>>>>>>> 6a7a41b34536667b9af969cbe9c39fb09d7988d1:smartqueue/notifications/migrations/0001_initial.py
            ],
        ),
    ]
